### ISSUE TITLE
Test framework improvements

### ISSUE THREAD

**Issue by jnewbery** [mit-dci/lit#61]
Once #60 is merged, we'll have a decent integration test framework that we can work on in parallel. Most of the test framework infrastructure has been separated from the test logic, so there's quite a large surface that we can work on without stepping on each others' toes. If anyone is interested in working on the tests, here's a grab bag of things that we could do:

- [x] #63 Refactor the `LitNode` class into its own module. Individual test cases can then subclass LitNode and override the `run_test()` method with their own test logic
- [x] #72 Actually test litecoin. I've added the framework for testing litecoin in bcnode.py, but haven't yet added test logic to do that
- [x] #64 Copy `combine_logs.py` from the [bitcoin repo](https://github.com/bitcoin/bitcoin/blob/master/test/functional/combine_logs.py). This combines logs from bitcoind and the test framework to give a total overview of what's happening in the test case. It'd be really useful to enhance this so it can ingest lit and litecoin logs as well, so we can see everything that's happening in the test case.
- [x] #68 Use python logging instead of `print()` - see https://github.com/bitcoin/bitcoin/pull/9768 for an example of how to do this
- [ ] Add lots of individual test cases:
    - [x] #65 opening/closing channels (cooperatively and uncooperatively)
    - [x] #65 sending payments between nodes
    - [x] #77 breaking a channel
    - [ ] transmitting an old channel state (justice!)
    - [ ] reorgs (not yet implemented)
    - [ ] multi-hop (not yet implemented)
    - [ ] multi-chain wallit with channels on each chain
    - [ ] atomic crosschain swaps (not yet implemented)
- [ ] Add interface to uspv from test_framework, so we can send P2P messages directly into lit instead of via a bitcoind node. That would allow us to test more edge cases.

We should also:
- [x] Integrate with [coveralls](https://coveralls.io/) so we can see code coverage
- [ ] write more unit tests

@vinchang2015 you mentioned you wanted to help with this. Let me know if you want to grab any of these tasks. I'm happy to give pointers/review code.

**Comment by JohnVonNeumann** [comment]
@jnewbery Does the coveralls integration have to be done by a repo owner? I'm aware many of the 3rd party integration type tasks do typically require admin ownership or something of the like. I'm happy to do some research into it and even implement if possible.

**Comment by jnewbery** [comment]
> Does the coveralls integration have to be done by a repo owner?

Yes, I believe so. I recommend you fork this repo, and then try coveralls on your fork. If you can get something running that you think is useful, then Tadge could enable it here.

**Comment by Varunram** [comment]
@jnewbery Coveralls is done!
